#!/bin/sh

export DB_DSN="root@tcp(localhost:3306)/aws-demo?charset=utf8&parseTime=true"
export DB_LOGGING="on"
export MEMCACHE="aws-demo-test.xfqx97.0001.usw2.cache.amazonaws.com:11211,aws-demo-test.xfqx97.0002.usw2.cache.amazonaws.com:11211"
export TEMPLATES="$PWD/templates"

gin
